sudo: false
language: php
php:
  - 8.0
matrix:
  fast_finish: true
before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction
script:
  - ./vendor/bin/phpunit --group memory
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '8.0' ]; then phpdbg -qrr ./vendor/bin/phpunit --exclude-group memory --coverage-clover /tmp/clover.xml; else ./vendor/bin/phpunit; fi"
after_script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '8.0' ]; then php ./vendor/bin/ocular code-coverage:upload --format=php-clover /tmp/clover.xml; fi"